name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Create writable temporary directory
      run: mkdir -p ${{ runner.temp }}/tmp_dir

    - name: Checkout code
      uses: actions/checkout@v2
      working_directory: ${{ runner.temp }}/tmp_dir/code

    - name: Set up Python in temporary directory
      run: |
        python_version='3.10'
        python_dir=${{ runner.temp }}/tmp_dir/python-$python_version
        python -m venv $python_dir
        source $python_dir/bin/activate
        pip install --upgrade pip

    - name: Install dependencies
      run: |
        source $python_dir/bin/activate
        pip install ${{ runner.temp }}/tmp_dir/code

    - name: Run tests
      run: |
        source $python_dir/bin/activate
        pytest ${{ runner.temp }}/tmp_dir/code/test
